---
name: CI

on: 
  push: 
    branches: 
      - "main"

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup | Golang
        uses: actions/setup-go@v4
        with:
         go-version: '>=1.17.0'
      - run: go version 

      - name: Build
        run: go build

      - name: Release Binary
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: gofetch
          name: gofetch
    
      - name: Make a pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files:  gofetch




